on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
name: Push
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.21.x]
    steps:
    - name: Install Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Test
      run: go test ./...
    - name: Vet 
      run: go vet ./...
